### ISSUE TITLE
XXMI or GIMI messing with game settings

### ISSUE THREAD

**Issue by JohnGit-hub** [SpectrumQT/XXMI-Launcher#10]
When launching genshin through xxmi the "dynamic character resolution" setting is automatically toggled off. When using GIMI as downloaded from gamebanana, the setting remains unchanged. Any ideas what is going on here?

I've noted that the GIMI version through XXMI is 8.01 which I can't find anywhere online, so I'm assuming it's something to do with that but don't know if there is any configuration I could do to stop this behavior.

**Comment by SpectrumQT** [comment]
GIMI is incompatible with DCR, thus launcher forcefully turns it off. There is no sense to have it enabled when you're modding the game with GIMI. And yes, launcher uses in-dev build of GIMIv8 that is not released yet, and it's also labeled as 'test' in launcher itself.

**Comment by JohnGit-hub** [comment]
I understand that, but I only use texture mods which are fully compatible with DCR. Would you consider implementing a toggle in the launcher? Or could you point me to where the genshin settings file is so I can set it as read only. Thanks.

**Comment by JohnGit-hub** [comment]
> GIMI is incompatible with DCR, thus launcher forcefully turns it off. There is no sense to have it enabled when you're modding the game with GIMI. And yes, launcher uses in-dev build of GIMIv8 that is not released yet, and it's also labeled as 'test' in launcher itself.

I understand that, but I only use texture mods which are fully compatible with DCR. Would you consider implementing a toggle in the launcher? Or could you point me to where the genshin settings file is so I can set it as read only. Thanks.

**Comment by JohnGit-hub** [comment]
Ah well looking through the gimi_package.py looks like it's modifying the registry, but I am stupid so I don't know if just removing the `self.disable_dcr()` function from `def initialize_game_launch(self, game_path: Path):` would cause any other issues.

**Comment by SpectrumQT** [comment]
Sounds fair. I've got your usecase. Added the toggle to my TODO list.
