### ISSUE TITLE
Wuthering Waves through XXMI doesnt Launch

### ISSUE THREAD

**Issue by PearGIT2323** [SpectrumQT/XXMI-Launcher#11]
Launching Wuthering waves through XXMI launcher causes it the game window to go transparent and unselectable 
![image](https://github.com/user-attachments/assets/58628cc5-f362-4328-9b7e-dbb3a268b6fd)
 
 Only works again after restarting the PC and reinstalling XXMI and C++

**Comment by SpectrumQT** [comment]
Check your antivirus software warnings and logs. It may be removing something. If that's not the case, I'll ned you xxmi launcher log from the xxmi launcher folder.

**Comment by SpectrumQT** [comment]
Also, I'm not sure if it was your [post on GB](https://gamebanana.com/questions/72067), but if not, you can try to forcefully run the launcher as admin.
