### ISSUE TITLE
[GIMI] Persistent variables are not being saved to d3dx_user.ini upon game close

### ISSUE THREAD

**Issue by lupomikti** [SpectrumQT/XXMI-Launcher#13]
Variables marked as persistent are not having their values saved in d3dx_user.ini when closing the game through normal means (opening the Paimon menu, clicking on Quit to get to the login screen, then clicking on Exit to exit the game). These variables are properly saved upon pressing the F10 shortcut to reload mods; it is only with game closure that the file is not being written to.

**Environment:**
- Windows 10 Pro 22H2, Build 19045.4780
- CPU: Ryzen 9 5900X, GPU: Radeon RX 6750XT
- 32GB RAM
- XXMI Launcher, GIMI folder, and Genshin Impact folders on same SSD drive which is not the C: drive
- GIMI folder is in a custom location, as I was using GIMI before XXMI was a thing

**Workaround:**
Since pressing F10 does save the persistent variables, the current workaround is to simply press this key before exiting the game.

**Comment by SpectrumQT** [comment]
It's expected behaviour of default 3dmigoto DLL. Adding auto-save to those vars is in my TODO list with low prio.

**Comment by lupomikti** [comment]
Cool, understood. If I wanted to work on that specific functionality myself, where would I be able to do that (and then submit a MR)? I'm guessing your 3DMigoto fork? I see the readme there is quite out-of-date, so what should I be aware of for development?

**Comment by SpectrumQT** [comment]
Yes, it's `SpectrumQT/3Dmigoto` repo. And yes, readme is just from cloned OG 3dmigoto repo. But you can read the list of commits to become up to date with what was changed by me.
