### ISSUE TITLE
SRMI Loading failed

### ISSUE THREAD

**Issue by mimmox** [SpectrumQT/XXMI-Launcher#14]
![Immagine 2024-10-02 223031](https://github.com/user-attachments/assets/859b7b99-a021-4c26-9c15-eee2fd3829ce)
Running with Admin but no work, I changed method with Hook, same problem

**Comment by SpectrumQT** [comment]
What's your OS and Anti-Virus? Does regular SRMI loader work for you?

**Comment by mimmox** [comment]
![Immagine 2024-09-29 030258](https://github.com/user-attachments/assets/8054d77d-c14f-4472-b9a9-953604847436)

It doesn't even work, as soon as I open it it closes by itself immediately.( For regular SRMI)
I have 360 ​​as an antivirus, but it is closed.

**Comment by SpectrumQT** [comment]
What's your OS version and build? From which distribution it was installed? It's an old rare issue swarming SRMI for ages, but neither I nor Silent were ever able to reproduce it tbh.

**Comment by mimmox** [comment]
windows 10 family
Ver:	22H2
Build 19045.4780

Hmm but first 2 months it worked, then this happened. I downloaded XXMI, it only worked for 2 times, then this problem comes out again

**Comment by SpectrumQT** [comment]
Well, I've made a dive into the C code used by injector library and haven't found any issues. It calls `OpenProcess` with correct `PROCESS_VM_OPERATION` flag required for `VirtualAllocEx` to work. In normal workflow, 
`VirtualAllocEx` may return `STATUS_ACCESS_DENIED` only if process handle acquired with `OpenProcess` has no `PROCESS_VM_OPERATION` access rights.
It means that if your OS is alright (and it most likely is, as you're not alone with the issue), than some third party mechanism interferes with normal execution, and with your input I can think only about Anti-Cheat. Unfortunately, it's where my capabilities cease to exist.
