### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by aogsi** [SpectrumQT/XXMI-Launcher#15]
I tried multiple times, but this error keeps recurring and I cannot download the launcher.
![image](https://github.com/user-attachments/assets/a929d2eb-7af5-4a15-907a-cb78311fe1e6)
![image](https://github.com/user-attachments/assets/71c8c419-4960-42aa-89ad-6a84ff86e38d)

**Comment by SpectrumQT** [comment]
It's general .msi installation error. Your system's Windows Installer fails to process the package. I'd suggest to try these solutions:
- [Run MSI File As Administrator From Command Prompt](https://www.intowindows.com/how-to-run-msi-file-as-administrator-from-command-prompt-in-windows/)
- [Check system time and Windows Installer permissions](https://answers.microsoft.com/en-us/windows/forum/all/called-runscript-when-not-marked-in-progress/912636bc-0214-4789-94f7-7b0af30f15be)
