### ISSUE TITLE
How to use system network proxy for XXMI?

### ISSUE THREAD

**Issue by SakiBiAnNya** [SpectrumQT/XXMI-Launcher#17]
I am in China. Due to some special reasons of China's network, I need to use VPN, but XXMI cannot recognize that I have used the system network proxy, which makes it impossible to update the version from within the software.
![6af35851596b6b060f3f805beec51abd](https://github.com/user-attachments/assets/d26b727d-6b50-4c9a-9ae4-57885bf7159a)

**Comment by SpectrumQT** [comment]
Most likely it's public proxy and GitHub API has limits of how often it can be called from the same IP. This error tells that said limit is exceeded for your proxy.

**Comment by SpectrumQT** [comment]
I'll try to address this problem later by adding option to specify personal access token. Also there's plan for standalone offline installer, but infrastructure for autobuilding isn't ready yet. For now, the only thing you can do is to change proxy.

**Comment by SpectrumQT** [comment]
With 1.6.0 update launcher now can be configured via Launcher Settings to use [Personal Access Token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens), as well as HTTPS or SOCKS5 proxy for GitHub connection.
