### ISSUE TITLE
Unable to launch the game

### ISSUE THREAD

**Issue by kehandoctor** [SpectrumQT/XXMI-Launcher#20]
Why can't you skip launching the game? Since using xxmi, every time you press F10 to switch mods, you may be kicked out of the game, and then start xxmi again to show that you can't start the game .exe, and you can't skip this step to use mods, the experience is too bad!
![屏幕截图 2024-10-19 085750](https://github.com/user-attachments/assets/f6267bef-0496-4b54-bf2e-3fd0cae8bf9e)

**Comment by SpectrumQT** [comment]
Your PC probably can't handle your modlist if F10 leads to disconnect or crash. As for the subsequent launch failure, you should solve the reason of being 'kicked out' first.
