### ISSUE TITLE
[GIMI] Enable HDR registry override 

### ISSUE THREAD

**Issue by zurce** [SpectrumQT/XXMI-Launcher#23]
Can an option for Enabling HDR through registry edit be added?  the key is `HKCU:\SOFTWARE\miHoYo\Genshin Impact\WINDOWS_HDR_ON_h3132281285` 

The limitation is that currently this needs to be executed on every run, since it clears back when the game launches, my previous setup involved a powershell script running the command

`Set-ItemProperty -Path "HKCU:\SOFTWARE\miHoYo\Genshin Impact" -Name WINDOWS_HDR_ON_h3132281285 -Value 1`

and waiting a couple of seconds, i tried adding this command in the prelaunch field but it doesn't seem to have any effect

**Comment by SpectrumQT** [comment]
Just put this command to vbs script and run it via pre-launch.

**Comment by Yashirow** [comment]
Doesn't work like that unfortunately. See this comment : https://github.com/SilentNightSound/GI-Model-Importer/issues/152#issuecomment-2081496891

**Comment by Kradziej** [comment]
It works fine just use a bat script

```
taskkill /F /IM "GenshinImpact.exe"

reg add "HKCU\SOFTWARE\miHoYo\Genshin Impact" /v WINDOWS_HDR_ON_h3132281285 /t REG_DWORD /d 1 /f

start /D "G:\Gry\Genshin Impact Unlocker\3dmigoto" 3DMigoto_Loader.exe
timeout /t 1
start /D "G:\Gry\Genshin Impact game" GenshinImpact.exe
```

Create shortcut -> properties -> advanced -> run as admin
Fix pathes
I also inject reshade because default HDR doesn't look that good, it's too bright

**Comment by Kradziej** [comment]
> Doesn't work like that unfortunately. See this comment : [SilentNightSound/GI-Model-Importer#152 (comment)](https://github.com/SilentNightSound/GI-Model-Importer/issues/152#issuecomment-2081496891)

Comment has nothing to do with this issue, I don't use this launcher I start the game and 3dmigoto with bat script but maybe it's a permission issue? Script must run as admin to modify registry

**Comment by SpectrumQT** [comment]
HDR support aka [SwapChain3 upcast](https://github.com/SilentNightSound/GI-Model-Importer/issues/152#issuecomment-2081496891) was added to DLL in [0.3.1 update](https://github.com/SpectrumQT/3Dmigoto/releases/tag/v0.3.1). You'll still need to enable HDR through registry tho, at least for now.

**Comment by Yashirow** [comment]
Works fine thanks a lot !

**Comment by SpectrumQT** [comment]
With **1.3.0** launcher update I've also added **Enable HDR** options to **General Settings**. When it's enabled, launcher will create required registry record automatically.
