### ISSUE TITLE
GIMI skin mod bug

### ISSUE THREAD

**Issue by ASDKICKOFF** [SpectrumQT/XXMI-Launcher#25]
when i downloaded GIMI and launched it the skins were broken (check the 5.1 update fixer) i tried using the skin fixer, didn't work. tried reinstalling orfix and tedfx didn't work. (it said Genshin model Importer version 8.0.3)

fixed it by reinstalling gimi from github and overwriting the installed GIMI (from XXMI) it says corrupt download and when i clicked restore and entered it was fixed.

btw this is for genshin, WUWA's works fantastically.
I leave this open since I fixed the issue on my own for my own pc but it's not for everybody.

i

**Comment by ASDKICKOFF** [comment]
btw this is for genshin, WUWA's works fantastically.

**Comment by ASDKICKOFF** [comment]
I leave this open since I fixed the issue on my own for my own pc but it's not for everybody.

**Comment by SpectrumQT** [comment]
This issue isn't related to launcher. Report GIMI issues to the GIMI GitHub or GB after GIMIv8 official release.
