### ISSUE TITLE
[GIMI] mods bug out

### ISSUE THREAD

**Issue by ASDKICKOFF** [SpectrumQT/XXMI-Launcher#27]
Mods bug out for me, all of them look crap, then i download the 7.0 version of GIMI; which fixed alot of the mods, except some.

After turning on the disabled orfix and the other things that got disabled (BufferValues) it got fixed.

why don't you include a skin fixer with the GIMI test? it would fix incompatibilities and make help with backward compatibility and improve the quality.

can you add an option to always ignore the suggestion made since it sucks.

Idk how to contact the one i should be contacting for GIMI test.

**Comment by SpectrumQT** [comment]
Current "mod fixers" aren't written in a way to be used as headless CLI tools aka by third party software like launcher. It's not safe neither for mods integrity nor for OS security. To include them "as is" would be the dumbest decision I could ever make. The proper universal patching engine is being discussed, but no one has enough time and motivation to implement it.

GIMIv8 is being developed by LeoTorezz in his [GIMI-TEST](https://github.com/leotorrez/GIMI-TEST/tree/main) repo mostly, and it's still an in-dev build.
