### ISSUE TITLE
Unable to Reinstall

### ISSUE THREAD

**Issue by BigDocJ** [SpectrumQT/XXMI-Launcher#28]
Manually deleted the files through file explorer for a reinstall and now unable to install program
![Screenshot 2024-11-03 183141](https://github.com/user-attachments/assets/3c2dd5b2-52d8-4ebb-8aab-94f0ae007d46)
![Screenshot 2024-11-03 183202](https://github.com/user-attachments/assets/b762c26d-8087-4ad3-afaa-7a18f20699d0)

**Comment by GreenTeaApples** [comment]
Mines doing the same thing, did you ever figure out what was wrong?
