### ISSUE TITLE
Detected: Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by highonbamboo** [SpectrumQT/XXMI-Launcher#3]
Installer 0.5.3 detected as a Trojan by Windows Defender.

**Comment by SpectrumQT** [comment]
Some picky AVs may be triggered by XXMI .exe or .dll files. Installer and Launcher are unsigned python apps compiled with Pyinstaller, that is [known to have false positives](https://discuss.python.org/t/pyinstaller-false-positive/43171).
