### ISSUE TITLE
Launch game by XXMI launcher make the game become stuck

### ISSUE THREAD

**Issue by AdriangnoH** [SpectrumQT/XXMI-Launcher#30]
I used GIMI to launch ZZZ before.It was running good.
And I want to play ZZZ with XXMI launcher now.The issue is when i launch game by XXMI launcher.The game becomes very stuck when I'm running down the street, but when i press esc, it looks normal and there is no lag.
I tried to copy GIMI's 3dmigoto.exe into the ZZMI which downloaded by XXMI launcher.It was also running good

**Comment by AdriangnoH** [comment]
By the way, I am Chinese and I cannot connect to github directly. I have to use proxy server to connect github.I don't know if this will have an impact.

**Comment by SpectrumQT** [comment]
You can try to lower the game process priority in General Settings. It may help on some systems. As for proxy, DLL itself doesn't have any web functionality, so it doesn't matter.

**Comment by AdriangnoH** [comment]
Doesn't work. I would go ask developer of ZZMI. Thank you.
