### ISSUE TITLE
Allow us to change mod loader versions

### ISSUE THREAD

**Issue by Arenity** [SpectrumQT/XXMI-Launcher#32]
I would like it if we could change the version of the mod loaders, eg. GIMI. All of my mods literally broke the moment I updated from GIMI test 8.0.2 to GIMI test 8.0.3 and I cant reroll the version as I cant find an option to reroll the version or find and download v8.0.2 and manually change the version.

**Comment by SpectrumQT** [comment]
All model importers are intended to be backwards compatible and allow user to not care about particular version. As stated in description and launcher, GIMI and SRMI packages are currently in-dev versions and are up for **public testing**. After official release, the latest version gonna also be the latest stable one.
