### ISSUE TITLE
Environment textures bug

### ISSUE THREAD

**Issue by Canfro** [SpectrumQT/XXMI-Launcher#34]
I've noticed that when playing Honkai Star Rail with XXMI, all my enviromental textures (floors, walls, details etc) look low quality and pixelated, asi if I were playing in very low settings. This only happens when I open the game with XXMI but when I play normally it's all good. What can I do? I don't think its a particular mod because when I disable mods with F6 the problem remains, and my PC can definately handle the high graphics

**Comment by SpectrumQT** [comment]
Try to test with empty ShaderFixes and Mods folders. F6 doesn't disable **everything**.
