### ISSUE TITLE
WWMI Missing and no GitHub connection

### ISSUE THREAD

**Issue by LeonidasMain** [SpectrumQT/XXMI-Launcher#35]
Yeah it is what the title says.
![Bild_2024-11-15_132516831](https://github.com/user-attachments/assets/2d375e1a-e0fc-4192-a3d5-b43ac4576a92)

WWMI is missing, i tried manually installing it but then it said that d311.dll is missing and i coulndt get my hands on this file. It said it ould download it via GitHub but since im apparently not connected to git it fails. Annoying af and i couldnt fix it need help pls.

![image](https://github.com/user-attachments/assets/562ed8d7-20ed-4ae5-965f-1e6b929708c7)
Before Manual installing WWMI 0.7.6

![Bild_2024-11-15_132818342](https://github.com/user-attachments/assets/2d00d91c-9846-417e-b70a-a55e7763d73c)
After trying to get d3d11.dll from Git

**Comment by SpectrumQT** [comment]
Your OS fails to provide basic HTTPS connectivity functions to the launcher. Check your AV, firewall, proxy, VPN or whatever for blocking connection.

**Comment by NoSanaNoLife-ctrladelete** [comment]
Please help, I have tried uninstalling and upon resintallation it shows me the error included in this post, I have tried installing with my antivirus turned off and it gives me the same error. I have scoured your issues section but you just tell people the same thing about turning off their antivirus, this obviously does not help the issue, I would really appreciate some more assistance please.

![Screenshot 2025-01-09 111540](https://github.com/user-attachments/assets/ff5fb236-001b-474d-97cf-4e9d69211bc9)

**Comment by SpectrumQT** [comment]
It's general HTTPS connection error, not a bug worthy a GitHub issue. There's nothing to fix. It means launcher cannot access the internet, something (i.e. firewall) is blocking access or system-wide VPN / Proxy is configured incorrectly.
