### ISSUE TITLE
Some WuWa mods stopped working with XXMI

### ISSUE THREAD

**Issue by zbingsong** [SpectrumQT/XXMI-Launcher#36]
I was using WWMI 0.7.1 previously and migrated to XXMI 1.1.1 today. I noticed that mods of Female Rover, Yangyang, Encore, and Taoqi stopped working for me. The characters appear as if no mods are applied at all. An example is the rover mod at https://gamebanana.com/mods/527028#H2_8.

Things I tried:
- Repair game with WuWa's official launcher. Shader gets recompiled.
- Have a clean install of XXMI 1.1.1.
- Only put one mod into the Mods folder.
- Use the 1.2, 1.3, and 1.4 fixes on the one mod, in this order.

After all of these, the problem persists. I'm not sure what is wrong. If I move the mod that is not working to WWMI 0.7.1's Mods folder, and use WWMI instead of XXMI, the mod just works. Could you please look into this issue and see if it is a problem of XXMi or an issue on my side?

**Comment by SpectrumQT** [comment]
Enable 0.6.X compatibility mode using Alt+F12.
