### ISSUE TITLE
How can I change the path?

### ISSUE THREAD

**Issue by Tsukuyo3** [SpectrumQT/XXMI-Launcher#39]
When I enable "force to 120 FPS", there is an error occurred like this.

![001](https://github.com/user-attachments/assets/69a440a7-1646-42fa-a953-368e3abedfaa)

I realize that the path of registry key for Star Rail CN Server is diffirent from Global Server. How can I change the path to let xxmi to find "GraphicsSettings_Model_h2986158309"?

![002](https://github.com/user-attachments/assets/35145256-f71d-407e-bdde-ad6036d8ccfe)

**Comment by Crostia** [comment]
你在通用设置的游戏路径选项没有用吗？他理应是跟随通用设置的游戏路径。另外，没记错的话这个帧率解锁应该不适用星铁，只能用在原神吧？

**Comment by SpectrumQT** [comment]
Well, you can manually tw
