### ISSUE TITLE
Cant turn off Users Guide

### ISSUE THREAD

**Issue by Tokoyak** [SpectrumQT/XXMI-Launcher#40]
Hi, so I downloaded WWMI and my mods work, but I can't close users guide. Is there any thing i can do with it? 
![obraz_2024-11-22_153040005](https://github.com/user-attachments/assets/84e39db4-494c-456d-8086-59f6f3b2d476)

**Comment by SpectrumQT** [comment]
Close the game and change `$\wwmiv1\first_run = 0` to `$\wwmiv1\first_run = 1` in **d3dx_user.ini** from `XXMI Launcher\WWMI` folder. Your OS seems to be failing to provide some basic functionality for whatever reason.

**Comment by Tokoyak** [comment]
Hi sorry to bother you again but i don't have d3dx_user.ini in any folder
what should i do?


pt., 22 lis 2024 o 21:13 SpectrumQT ***@***.***> napisał(a):

**Comment by SpectrumQT** [comment]
Well, it means that 3dmigoto fails to work properly in your OS. Probably something like AV is blocking d3d11.dll from reading keyboard input and writing files. You should solve those issues first.
