### ISSUE TITLE
Parameter to open Wuthering Waves directly from command line (used for Playnite)

### ISSUE THREAD

**Issue by Wilann** [SpectrumQT/XXMI-Launcher#41]
Hi, I'm trying to create a set-up where Playnite will open the XXMI launcher which will open Wuthering Waves immediately. 

In my playnite settings I have the XXMI `.exe` launcher as my [Path](https://api.playnite.link/docs/manual/library/games/gameActions.html#:~:text=Path,URL\)%20to%20start.).

The "Arguments" field, defined as [Arguments | Startup arguments passed to an executable during startup](https://api.playnite.link/docs/manual/library/games/gameActions.html#:~:text=Arguments,executable%20during%20startup.) can be used to start a game immediately, but I'm not sure what to put there. I tried searching the repo but didn't find any hints.

I would be greatful if you could lead me in the right direction. Thank you! 

</body>
</html>

![image](https://github.com/user-attachments/assets/535b552d-b093-4da5-8237-635365bb647f)

**Comment by SpectrumQT** [comment]
Hello. I guess you want to use the combination of the following two arguments:
`--xxmi WWMI`: Set active model importer used by launcher to WWMI.
`--nogui`: Start game with active model importer without showing launcher window.
So `--xxmi WWMI --nogui` it is.
