### ISSUE TITLE
INI Parser Warnings Not Displaying Text

### ISSUE THREAD

**Issue by alphasprt** [SpectrumQT/XXMI-Launcher#43]
Current warning system dosen't recognize characters from other languages like Chineese or Korean.

Thus, If the direrctory of the ini(s) which causes warnings includes them, only the BEEP happens. Warning text doesn't appear. 
That prevents me from fixing the issue.

I know i can disable warnings completly, but i cant live with inis with flaws inside my mod folders.
Also i have so many mods that i cannot just manually search for the cause.

I know intergrating chineese or korean is difficult. especially for those who don't speak them.
i think logging the warnings into txt should work.
(i tried enabling every logging but none of them included ini warnings)

**Comment by SpectrumQT** [comment]
Unless someone wants to commit required major rewrite of notification system, this won't be happening. Use ASCII characters in folders names if you want them to be shown correctly. I'll fix the display itself via replacing invalid chars with `?` though.

**Comment by alphasprt** [comment]
I am doing exactly that, but there are so many folders. 
i must have missed some, and i couldnt find the missed ones. 
the question mark thing would do the job. thanks.

**Comment by SpectrumQT** [comment]
Overall UTF-8 paths support and display of unknown chars as `?` were added to XXMI DLL in [0.3.1 update](https://github.com/SpectrumQT/3Dmigoto/releases/tag/v0.3.1).
