### ISSUE TITLE
what's wrong?

### ISSUE THREAD

**Issue by MRbuty** [SpectrumQT/XXMI-Launcher#44]
![屏幕截图 2024-11-24 160122](https://github.com/user-attachments/assets/5d9ab026-5f2a-4aff-8c5f-fdf0a646feb8)
what can i do for it?

**Comment by MRbuty** [comment]
![屏幕截图 2024-11-24 160429](https://github.com/user-attachments/assets/fcbe2d72-3021-41a6-a13b-40317f1779df)

**Comment by SpectrumQT** [comment]
Fix your internet connection obviously.
