### ISSUE TITLE
can not reinstall to anther directory

### ISSUE THREAD

**Issue by ZhuWenxuan123code** [SpectrumQT/XXMI-Launcher#45]
I thought a new folder would be created automatically, so I installed it in the root directory by mistake. Then I simply deleted all the files. After that, I wanted to install again, and I was prompted,"XXMI Launcher is already installed!" In fact, I have deleted it, what should I do? I was too stupid to just delete it.

**Comment by ZhuWenxuan123code** [comment]
![Uploading image.png…]()

**Comment by ZhuWenxuan123code** [comment]
![Snipaste_2024-11-24_18-59-13](https://github.com/user-attachments/assets/1ecbcc95-4b6c-4498-b5d4-54b2e4670ead)

**Comment by ZhuWenxuan123code** [comment]
solved

**Comment by Lamark28** [comment]
I would love to know how this was solved if possible?

**Comment by ZhuWenxuan123code** [comment]
i used a software，“geek”
