### ISSUE TITLE
Can't load additional services alongside XXMI

### ISSUE THREAD

**Issue by advanced03** [SpectrumQT/XXMI-Launcher#47]
Hello guys.

I'm using SpecialK alongside Wuthering Waves for a few options.

I've tried many things, like using the SpecialK dll with XXMI, putting special K in the launch options etc.

But none of these loaded SpecialK alongside XXMI.

My question is, can I load SpecialK? Or is there a technical limitation preventing me from doing so?

**Comment by SpectrumQT** [comment]
Hello! XXMI DLL is 3dmigoto DLL fork. You can try your luck [searching for it instead](https://github.com/bo3b/3Dmigoto/issues/190). I won't be able to tell you more than DarkStarSword.

Launcher itself provides you means to either:
1. Run game and Inject (WriteProcessMemory) extra DLL **after** 3dmigoto DLL via Inject Libraries.
2. Do your own stuff (aka run any command line) **before** game start and 3dmigoto DLL injection via Run Pre Load.
3. Do your own stuff **after** game start and 3dmigoto injection with Run Post Load.
4. Run game yourself, do whatever you want and then automatically inject 3dmigoto DLL via Custom Launch.

**Comment by advanced03** [comment]
So it's possible to run the game myself and have the XXMI inject afterwards? How can I do this?

I used the same method with the older WWMI.

**Comment by SpectrumQT** [comment]
4. Run game yourself, do whatever you want and then automatically inject 3dmigoto DLL via Custom Launch.

So just point Custom Launch to .bat or .cmd or .vbs script or executable that would launch the game and inject your DLL in it.

**Comment by advanced03** [comment]
You mean the XXMI dll?

**Comment by advanced03** [comment]
> I mean SpecialIK or whatever else. Launcher will wait till your **blocking** Custom Launch command is executed, than it'll locate the game process you (aka your script) started and inject XXMI dll aka 3dmigoto aka d3d11.dll.

Okay thanks, I will use the same executable path that special K uses hopefully that will inject both into the game.

Will update later

**Comment by advanced03** [comment]
@SpectrumQT  Okay so it worked but I see the message "Ensuring the game is closed". 

It's closing the game so XXMI can launch the game itself, is there any way to get around or disable the questions?

Sorry if I'm asking too many questions I'm not really familliar with combining these tools.

**Comment by SpectrumQT** [comment]
Please give me a screenshot of your Advanced Settings and launcher log file from its folder. With configured Custom Launch, it shouldn't try to close the game... unless there's some bug involved.

**Comment by advanced03** [comment]
![{D16A127E-FC78-4383-BC5D-544B2451B44B}](https://github.com/user-attachments/assets/4754de98-1e1b-46bc-8660-fb9ffa87e3e9)
Okay I think I did it correctly this time using the custom launch like you said, let the tool open SpecialK and then I use SpecialK to la
[SKIF.log](https://github.com/user-attachments/files/17924768/SKIF.log)
[SKIF_launcher.log](https://github.com/user-attachments/files/17924770/SKIF_launcher.log)
unch the game.

Unfortunately It's giving me UE4 fatal error no matter if I choose Hook or Inject

**Comment by SpectrumQT** [comment]
Well, I expected you to at least read the tooltip before asking. For WuWa, you should start the game exe in DX11 mode. Required arguments are in the tooltip.

**Comment by advanced03** [comment]
> Well, I expected you to at least read the tooltip before asking. For WuWa, you should start the game exe in DX11 mode. Required arguments are in the tooltip.

Excuse me? I've read all the tooltips and the game is being launched with DX11.

**Comment by SpectrumQT** [comment]
But I can clearly see in the log that wrong argument `-dx11` is being used to launch the game exe.

**Comment by advanced03** [comment]
> But I can clearly see in the log that wrong argument `-dx11` is being used to launch the game exe.
Weird, I use d3d11 which I'm pretty sure is the right one?

**Comment by SpectrumQT** [comment]
Please, read the warnings in the Custom Launch tooltip. It has required arguments.

**Comment by advanced03** [comment]
?
![{CDA5D964-369E-4C4D-9F9D-054E4AA492A5}](https://github.com/user-attachments/assets/c2de5ae0-334c-4c55-a2ab-cbd2c368be37)
![{59DABC7B-6529-4527-8086-1F813B3F5DB5}](https://github.com/user-attachments/assets/9dd538d2-8256-4c12-8b72-62dea165ac91)

I think I know how to get around the fatal errors, but for that I need XXMI to not launch the game.
Is there no way to manually launch the game yourself, instead of XXMI handle it?

**Comment by SpectrumQT** [comment]
![firefox_to1sdKDyoO](https://github.com/user-attachments/assets/f17a0b40-d8c4-4a6b-a635-cbb339eb1666)

**Comment by advanced03** [comment]
> ![firefox_to1sdKDyoO](https://private-user-images.githubusercontent.com/19625504/390123896-f17a0b40-d8c4-4a6b-a635-cbb339eb1666.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NTIwOTEsIm5iZiI6MTczMjY1MTc5MSwicGF0aCI6Ii8xOTYyNTUwNC8zOTAxMjM4OTYtZjE3YTBiNDAtZDhjNC00YTZiLWE2MzUtY2JiMzM5ZWIxNjY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDIwMDk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1ZTAyZWZmZDM4NmVkN2Y1ZGM3M2Q4NjBmNDRjYmYxNzY2MjY3Y2UxMDg3NDMwZjA2MDNhODY5NzcxMGFkMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J52HezM3aL86OnPHe74GdnvBaghnOcF4O7Uo1tdZbX4)


Okay so first off, this tooltip isn't even in the wuthering waves tab so I don't know why you're blaming me for that. 

Second, I don't know if you're actually reading my messages or not, but the game is already running in DX11. The problem lies with the fact that if XXMI launches the game, it produces a UE4 Fatal error.

The workaround of leaving the game folder empty doesn't work anymore, since you've implemented some kind of verification for it.

**Comment by SpectrumQT** [comment]
The tooltip in question is set for the very field you're filling the Custom Launch command in. And same for me, it looks like you're ignoring my messages and logs of your application. Okay, let me phrase it one more time.

1. If **Custom Launch** is set, launcher **does not** try to launch the game. It only waits for `Client-Win64-Shipping.exe` process to spawn until 30s timeout.
2. The `SKIF.log` clearly states that `C:\Program Files\Special K\SKIF.exe` (**not** launcher) tries to launch `Client-Win64-Shipping.exe` with `-dx11`, while correct way to force DX11 is `Client -DisableModule=streamline`. And let me guess, it worked for old WWMI long ago, while (surprise!) devs changed how game works with updates.

Sorry, but I don't appreciate this kind of conversation. No futher help will be provided.

**Comment by advanced03** [comment]
> The tooltip in question is set for the very field you're filling the Custom Launch command in. And same for me, it looks like you're ignoring my messages and logs of your application. Okay, let me phrase it one more time.
> 
>     1. If **Custom Launch** is set, launcher **does not** try to launch the game. It only waits for `Client-Win64-Shipping.exe` process to spawn until 30s timeout.
> 
>     2. The `SKIF.log` clearly states that `C:\Program Files\Special K\SKIF.exe` (**not** launcher) tries to launch `Client-Win64-Shipping.exe` with `-dx11`, while correct way to force DX11 is `Client -DisableModule=streamline`. And let me guess, it worked for old WWMI long ago, while (surprise!) devs changed how game works with updates.
> 
> 
> Sorry, but I don't appreciate this kind of conversation. No futher help will be provided.

Maybe because you're lying through your teeth? Literally take one look and my screenshot and you can see the tooltip for Wuthering Waves is very different to the one you've showed. I'm not sure why you insist that it's there.
