### ISSUE TITLE
Can I install two XXMI launchers?

### ISSUE THREAD

**Issue by Cathesth** [SpectrumQT/XXMI-Launcher#49]
I want to run my main account and my secondary account through this program.

I don't want to log out and log in every time or change the path to the game in the launcher. 

So I would like to install two launchers and run games from my main account on one launcher and games from my second account on the other launcher.

Can you tell me if this is possible and if not, is there another way to do it?

**Comment by SpectrumQT** [comment]
Hello! As of now, there isn't a **proper** way to do so. But, if you're okay with manual **launcher** updates for the second instance, you can use .zip version from downloads, extracted in a different folder. So whenever first one gets **launcher** update, just download it's .zip and extract it to secondary folder.

**Comment by SpectrumQT** [comment]
Now it's possible to achieve with portable launcher version. While you still can have only one active `.msi` installation, number of portable installations is unlimited.
