### ISSUE TITLE
FixDash.ini incompatible with Dynamic Character Resolution

### ISSUE THREAD

**Issue by Yashirow** [SpectrumQT/XXMI-Launcher#50]
I know the `Dynamic Character Resolution` setting should be disabled when playing with mods but since I play only with 4k characters upscales I don't need to.

The version of the `FixDash.ini` used by your GIMI version doesn't works with this setting while [this one](https://github.com/LeoTorreZ/LeoTools/blob/main/releases/FixDash.ini) works perfectly fine. I'm not familiar with GIMI shadder modding but looks like only some hashes are changed between the two versions.

**Comment by leotorrez** [comment]
That "fix" linked is very dated and therefore it likely does nothing anymore. Feel free to delete FixDash.ini from your mods if it helps with your peculiarly nieche case
