### ISSUE TITLE
d3d11.dll is missing expected entry point

### ISSUE THREAD

**Issue by gptlang** [SpectrumQT/XXMI-Launcher#51]
![image](https://github.com/user-attachments/assets/fcc4035a-49dc-44e2-9874-9f09dc4a16a9)

**Comment by SpectrumQT** [comment]
It looks like you're trying to load custom d3d11.dll or your OS is broken beyond repair. In first case, repair feom 3 dots menu will help. Can't help with second.

**Comment by gptlang** [comment]
It's the unmodified d3d11.dll. No modifications have been made. Running https://github.com/leotorrez/ZZ-Model-Importer directly worked after renaming d3d11.dll to 3dmigoto.dll and changing the config accordingly. Seems to be something specific to the filename.

**Comment by SpectrumQT** [comment]
Well, it may happen only if your OS serves wrong DLL (i.e. real d3d11.dll) via `LoadLibraryExW`. Try to reboot the system. Also, please share your launcher log from its folder.

**Comment by SpectrumQT** [comment]
Please also provide `XXMI Launcher Log.txt` from the XXMI Launcher root folder.
And what's your OS and GPU?

**Comment by gptlang** [comment]
Fedora, Intel Iris Xe Graphics.

**Comment by gptlang** [comment]
Oh wtf it just worked

**Comment by gptlang** [comment]
The fix was to disable VKD3D and NVAPI and launch from Lutris.

**Comment by kevinoon** [comment]
Hey
