### ISSUE TITLE
Error GlMl Loading Failed:failed to disable DCR， graphic settings are not found！

### ISSUE THREAD

**Issue by zhanzheniaoniao** [SpectrumQT/XXMI-Launcher#53]
I deleted a file that I didn't think was important, so much so that Gimi that would have worked had the following problem, what can I do to remedy it. (Thank you very much)
![{4A5BF677-1474-477B-A3FB-8B7850043C8A}](https://github.com/user-attachments/assets/03968180-b45e-42b1-a604-557b058e5f8c)

**Comment by SpectrumQT** [comment]
Did you try to do exactly what the launcher suggests you to do? Aka `Please start the game once with official launcher!`

**Comment by zhanzheniaoniao** [comment]
Yes, the software I downloaded on github and it worked yesterday, but now it's like this. Do you know where the problem is.

**Comment by zhanzheniaoniao** [comment]
> 您是否尝试完全按照启动器建议的那样去做？即`Please start the game once with official launcher!`



> Did you try to do exactly what the launcher suggests you to do? Aka `Please start the game once with official launcher!`
Yes, the software I downloaded on github and it worked yesterday, but now it's like this. Do you know where the problem is.

**Comment by SpectrumQT** [comment]
There's something wrong with GI registry record. Uncheck Disable DCR option in launcher's general settings and disable it manually in-game. And please don't spam the issues.
