### ISSUE TITLE
Unable to quit Genshin Normally when in use

### ISSUE THREAD

**Issue by RickyHunter024** [SpectrumQT/XXMI-Launcher#55]
Hello, I would like to report a bug which seems to be related to GIMI, the version used in the latest public release of XXMI Launcher as if 19th December 2024. When I quit the game even with no mods installed I always have to kill it either thru task manager or wait for windows to detect the app ain't working and giving me that prompt to forcefully close it.

**Comment by SpectrumQT** [comment]
Unloading of `d3d11.dll` during game shutdown is handled by the game engine and OS. Most likely the issue is caused by some unique interaction between OS/AC/AV/Game/Software on your machine and just can't be fixed. Does it happen both for 120 FPS option enabled and disabled?

**Comment by SpectrumQT** [comment]
Just test with both, as it's the easiest way to test both dll injection methods for GI.

**Comment by SpectrumQT** [comment]
With 1.2.0 update launcher now explicitly frees the `d3d11.dll` after its injection, tho it should only have any effect if `Close After Game Start` option is **disabled** (aka if launcher stays open after the game launch). Potentially it could conflict with some weird AVs. It's unlikely to solve reported issue, but still worth to try.
