### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Legnatbird** [SpectrumQT/XXMI-Launcher#58]
![{F0A4B5CE-D4E2-4B77-A959-F22505513C41}](https://github.com/user-attachments/assets/6255f951-3643-4ef0-8e3e-290a8383be0c)
After find a way to install as admin said this
![image](https://github.com/user-attachments/assets/9fbca68e-f735-48db-b088-19107818d74d)

**Comment by Gian-UC** [comment]
In addition to this error, when installing, the launcher does not appear when you click to open, only the Windows security notification appears.

**Comment by SpectrumQT** [comment]
Please refer to google for solutions for Windows Installer errors. If OS fails to install `.msi`, it's OS fault.
