### ISSUE TITLE
Automatic updates are not possible

### ISSUE THREAD

**Issue by Gpan666** [SpectrumQT/XXMI-Launcher#62]
![QQ20241226-121441](https://github.com/user-attachments/assets/964e1aef-6245-4fd9-8be6-051714a0ce3d)
An error will be reported when using automatic updates, regardless of whether the default path is used or not

**Comment by SpectrumQT** [comment]
So it doesn't go past the "Preparing to install" window? Check your anti-virus, it may blocking the install. If nothing helps, you can try to uninstall .msi via control panel and switch to portable launcher version, it has its own update mechanism.

**Comment by Gpan666** [comment]
> 所以它不会通过“准备安装”窗口？检查您的防病毒软件，它可能会阻止安装。如果没有任何帮助，您可以尝试通过控制面板卸载.msi并切换到便携式启动器版本，它有自己的更新机制。

我没有安装杀毒软件，微软自带的也关闭了，控制面板卸载.msi是指卸载xxml后重新安装吗？还是什么呢。

**Comment by SpectrumQT** [comment]
Yes, you can uninstall launcher via control panel and than extract zip version in the same folder.
