### ISSUE TITLE
Windows Security Threat Found : Trojan:Win32/Bearfoos.A!ml

### ISSUE THREAD

**Issue by CrimesCU** [SpectrumQT/XXMI-Launcher#63]
It seems that your most recent change to the code has annoyed Windows Security. I was playing earlier a few hours ago with no issue, when I tried to start the ZZMI now Windows flagged the d3d11.dll file up as a Trojan.
![image](https://github.com/user-attachments/assets/8c10b4dd-d22b-4979-bc9f-120fffa17070)

**Comment by SpectrumQT** [comment]
[https://www.virustotal.com/gui/file/8a595742304fa71185a2c1173a851e0bdc61d220b6c26a6ec589b7738d4bb21a](https://www.virustotal.com/gui/file/8a595742304fa71185a2c1173a851e0bdc61d220b6c26a6ec589b7738d4bb21a)
And `ml` in threat means "machine learning" detection. And no, I won't be rolling back [important DLL fix](https://github.com/SpectrumQT/3Dmigoto/releases) because of some dumb neural network.

**Comment by MANUUo** [comment]
> It seems that your most recent change to the code has annoyed Windows Security. I was playing earlier a few hours ago with no issue, when I tried to start the ZZMI now Windows flagged the d3d11.dll file up as a Trojan. ![image](https://private-user-images.githubusercontent.com/192928644/398815330-8c10b4dd-d22b-4979-bc9f-120fffa17070.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyNzc1MTgsIm5iZiI6MTczNTI3NzIxOCwicGF0aCI6Ii8xOTI5Mjg2NDQvMzk4ODE1MzMwLThjMTBiNGRkLWQyMmItNDk3OS1iYzlmLTEyMGZmZmExNzA3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QwNTI2NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzAwZDZlZjZiOWZiMWI4ODkxZGYwM2Q5N2EwNjQ0ODczODgyODRlZmJmMTUyYzExZWY3YzQ1Njg2ZDg4NGQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vPREN4KRrHVwPfmmDzXUnMitoKXIiVExFfgo3x63URw)
> 
> Edit: Tried to install a previous version of XXMI to get around it, but it seems to download the latest ZZMI version anyway so it doesn't seem to make much of a difference there.

>Edit: The same thing happens to me, my Windows Defender automatically deletes it and then the xxmi launcher says that it did not find the file
