### ISSUE TITLE
Why the application can not run on my pc?

### ISSUE THREAD

**Issue by AstraeaGM** [SpectrumQT/XXMI-Launcher#65]
As the title said ,i tried your two release.
1.The installer: it notice me as the picture below. i had uninstalled all the programs and del all the files which it's about the older version.
![2024-12-28-21点57分](https://github.com/user-attachments/assets/ca677f47-5e81-4f46-b3bd-bc2f07ec0f80)
2.The portable zip:
No matter run as the admin or reboot the computer , i can't run the XXMI Launcher.exe after double clicking the program.
After double clicking the launcher, the mouse icon becomes "loading..." and then nothing happened.

**Comment by SpectrumQT** [comment]
Does portable launcher at least create log in its folder? As for .msi, you can tey to use apps like CCleaner to remove lefltover traces. Anyway, there's something terribly wrong about your OS.

**Comment by AstraeaGM** [comment]
> Does portable launcher at least create log in its folder? As for .msi, you can tey to use apps like CCleaner to remove lefltover traces. Anyway, there's something terribly wrong about your OS.

Thank you for your answer, i tried "windows install clean up" program to clean my OS , finally i can install and use your app.
