### ISSUE TITLE
How to use xxmi tool with korepi?

### ISSUE THREAD

**Issue by hungvn2k5** [SpectrumQT/XXMI-Launcher#9]
How to use xxmi tool with korepi?
it said that "failed to inject d3d11.dll to Genshin Impact".

**Comment by SpectrumQT** [comment]
Refer to the **Run Pre-Launch** and **Custom Launch** in **Advanced Settings** to launch game with / via 3rd-party software. Please do note that I provide no support related to the 3-rd party apps themselves and can't guarantee compatibility.
